version: "3.3"

services:
  backend-api:
    build: ./backend/node
    restart: always
    # working directory in container to place files
    working_dir: /usr/src/app
    # startup command if it takes a long time uncomment line 31 and comment line 30, if you do this 
    #   you must run `yarn` at the package.json level locally prior to starting
    command: bash -c "yarn && yarn run dev"
    # command: bash -c "yarn run dev"
    # map code volumes from local to inside working directory, changes made locally will update into the container
    volumes:
      - ./backend/node:/usr/src/app
    # ports to map, YOU CANNOT RUN ANYTHING ELSE ON PORT 8000
    ports:
      - 8001:8000
    # shared network
    networks:
      - api

  frontend-app:
    tty: true
    build: ./frontend
    restart: always
    # working directory in container to place files
    working_dir: /usr/src/app
    # startup command if it takes a long time uncomment line 51 and comment line 50, if you do this 
    #   you must run `yarn` at the package.json level locally prior to starting
    command: bash -c "yarn && yarn start"
    # command: bash -c "yarn start"
    # map code volumes from local to inside working directory, changes made locally will update into the container
    volumes:
      - ./frontend:/usr/src/app
    # specify dependency on mysql db
    depends_on:
      - backend-api
    # ports to map, YOU CANNOT RUN ANYTHING ELSE ON PORT 3000
    ports:
      - 3001:3000
    # shared network
    networks:
      - api



# specify networks
networks:
  api:

# persistent volume, comment all out if not using db_vol above
volumes:
  db_vol:
